name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-build-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-node-modules-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn package

      - name: Post-Build
        if: runner.os == 'Windows'
        run: |
          mkdir build
          mv out/*/* build/
          mv build/LICENSE build/LICENSE.electron
          cp LICENSE build/LICENSE

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pokemon-cafe-reservation-notifier-${{ runner.os }}
          path: |
            build/
